MyIP: 127.0.0.1
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${MyIP}:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
  redis:
    host: ${MyIP}
    port: 6379
  session:
    store-type: redis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    root: warn

